name: Create Flat Zip for Obsidian Plugin Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create flat zip without parent folder
        run: |
          zip -r cryptoprotos.zip manifest.json main.js README.md license.me *.css *.md *.json

      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: cryptoprotos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
